<a href="https://colab.research.google.com/github/ai2ys/Python-Cheat-Sheet-As-Jupyter-Notebooks/blob/master/python_cheat_sheet_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Beginners tutorial - arrays in NumPy

This is my 'cheat sheet' for creating and handling arrays in Numpy. Topics are

Create arrays
Crop and subsample arrays
Mulitplications of an array with another array or scalar

In [2]:
import numpy as np
np.__version__

'1.19.5'

## Array creation routines
The following link gives an overview of array creation routines. https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

### Create an array of zeros, ones, or an empty array
- `np.zeros`
- `np.ones`
- `np.empty` → does not initialize the array entries and is therefore slightly faster than `np.zeros`

In [12]:
rows = 2000
columns = 3000

In [13]:
%time array_empty = np.empty((rows, columns))
print('shape', array_empty.shape)

CPU times: user 94 µs, sys: 14 µs, total: 108 µs
Wall time: 111 µs
shape (2000, 3000)


In [14]:
%time array_zeros = np.zeros((rows, columns))
print('shape', array_zeros.shape)

CPU times: user 4.18 ms, sys: 24.9 ms, total: 29.1 ms
Wall time: 29.8 ms
shape (2000, 3000)


In [15]:
%time array_ones = np.ones((rows, columns))
print('shape', array_ones.shape)

CPU times: user 1.53 ms, sys: 14.1 ms, total: 15.6 ms
Wall time: 19.4 ms
shape (2000, 3000)


### Create a 1D array of equally spaced numbers
https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html

- `numpy.arange`
- `numpy.linspace`

Create an array with integers from `0` to `9` using `np.arange(10)`. Have in mind that the stop value (here: `10`) is not included.

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create an array with a specified start, stop, and step size. As mentioned before the stop value is not included.

In [17]:
np.arange(start=5, stop=30, step=5)

array([ 5, 10, 15, 20, 25])

In case of using non-integer step sizes the NumPy documentation recommends to use numpy.linspace instead.

In [18]:
np.arange(start=0, stop=1, step=0.1, dtype=np.float)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In contrast to `np.arange` the method `np.linspace` offeres the option to include or exclude the endpoint. But keep in mind that you have to adjust the parameters to get the same spacing.

In [20]:
start = 0
num = 10
print(np.linspace(start=start, stop=1, endpoint=False, num=num))
print(np.linspace(start=start, stop=1, endpoint=True, num=num))
print(np.linspace(start=start, stop=0.9, endpoint=True, num=num))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## Crop and subsample arrays
Crops can be extracted from arrays and they can be subsampled as well. Here an example for subsampling an array.

- `array[index]`
- `array[start:stop]`
- `array[start:stop:step]`

In [21]:
step_size = 10
start = 0
data_1D = np.arange(101)
data_1D[start::step_size]

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Example for creating a crop. Have in mind that the endpoint will not be included.

In [22]:
start = 12
end = 50
data_1D = np.arange(101)
data_1D[start:end]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49])

Extract the last element of an array by using the index `-1`. To access the second last elment use the index `-2` and so on.

In [23]:
data_1D = np.arange(10)
print(data_1D)
print('index -1:', data_1D[-1])
print('index -2:', data_1D[-2])

[0 1 2 3 4 5 6 7 8 9]
index -1: 9
index -2: 8


But have in mind that using the index `-1` as endpoint in order to crop a portion of the source array will exclude the last element of the source array.

In [24]:
data_1D[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

The zero as startpoint can be ommitted.

In [25]:
data_1D[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Array multiplications
Types of multiplications

- Matrix with scalar<br>
`array * scalar`
- Element-wise product of two arrays<br>
`array_a * array_b or np.multiply(array_a, array_b)`
- Dot product of two arrays<br>
`array_a.dot(array_b) or np.dot(array_a, array_b)`

In [26]:
array_a = np.arange(start=0,stop=4)
array_b = np.arange(start=2,stop=6)
print(array_a)
print(array_b)

[0 1 2 3]
[2 3 4 5]


In [27]:
# array * scalar
scalar=3
array_a * scalar

array([0, 3, 6, 9])

In [28]:
# element-wise multiplication (equivalent to Matlab: a .* b)
print(np.multiply(array_a, array_b))
print(array_a * array_b)

[ 0  3  8 15]
[ 0  3  8 15]


In [29]:
array_a * array_b

array([ 0,  3,  8, 15])

## Stacking arrays in depth

In [30]:
array_list = [np.arange(start=0, stop=10), np.arange(start=10, stop=20), np.arange(start=20, stop=30)]
print(array_list)
arrays_stacked = np.dstack(array_list)
print(arrays_stacked)
print('shape', arrays_stacked.shape)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])]
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]]
shape (1, 10, 3)
