<a href="https://colab.research.google.com/github/ai2ys/Python-Cheat-Sheet-As-Jupyter-Notebooks/blob/master/python_cheat_sheet_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Cheat Sheet - NumPy Array

This is my 'cheat sheet' for creating and handling arrays in Numpy. Topics are

- Create arrays
- Crop and subsample arrays
- Mulitplications of an array with another array or scalar

In [1]:
import numpy as np
np.__version__

'1.19.5'

## Array creation routines
The following link gives an overview of array creation routines.    
https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

### Create an array of zeros, ones, or an empty array
- `np.zeros`
- `np.ones`
- `np.empty` → does not initialize the array entries and is therefore faster than `np.zeros` and `np.ones`

Comparing create time with 2D array creation below.

In [3]:
rows = 2000
columns = 3000

Using `np.empty`

In [4]:
%time array_empty = np.empty((rows, columns))
print('shape', array_empty.shape)

CPU times: user 248 µs, sys: 46 µs, total: 294 µs
Wall time: 1.62 ms
shape (2000, 3000)


Using `np.zeros`

In [5]:
%time array_zeros = np.zeros((rows, columns))
print('shape', array_zeros.shape)

CPU times: user 4.22 ms, sys: 25.2 ms, total: 29.4 ms
Wall time: 30.3 ms
shape (2000, 3000)


Using `np.ones`

In [7]:

%time array_ones = np.ones((rows, columns))
print('shape', array_ones.shape)

CPU times: user 5.71 ms, sys: 17.4 ms, total: 23.1 ms
Wall time: 30.7 ms
shape (2000, 3000)


### Create a 1D array of equally spaced numbers
https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html

- `numpy.arange`
- `numpy.linspace`

Create an array with integers from `0` to `9` using `np.arange(10)`. Keep in mind that the stop value (here: `10`) is not included.

Using `np.arrange(10)` will create an array containing all integer values from `0` to `9`. Without specifying explicitly the start value will be `0` and the step size will be `1`. 

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create an array with a specified start, stop, and step size. As mentioned previously the stop value is not included.

In [ ]:
np.arange(start=5, stop=30, step=5)

array([ 5, 10, 15, 20, 25])

Here an example with an non-integer step size. The NumPy documentation recommends to use `np.linspace` instead of `np.arrange` with non-integer step sizes.

In [ ]:
np.arange(start=0, stop=1, step=0.1, dtype=np.float)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In contrast to `np.arange` the method `np.linspace` offeres the option to include or exclude the endpoint. But keep in mind that you have to adjust the parameters to get the same spacing.

In [22]:
start = 0
num = 10

In [18]:
np.linspace(start=start, stop=1, endpoint=False, num=num)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [19]:
np.linspace(start=start, stop=0.9, endpoint=True, num=num)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [21]:
np.linspace(start=start, stop=1, endpoint=True , num=num)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Selecting array elements, crop and subsample arrays
Crops can be extracted from arrays and they can be subsampled as well. Here an example for subsampling an array.

Indices in Python are zero-based and the `stop`-index value will not be included.
- `array[index]` &rarr; accessing an array element by its index
- `array[start:stop]` &rarr; extracting a slice of the array containing all values from index `start` to `stop-1`
- `array[start:stop:step]` &rarr; extracting a slice of the array containing only n-th value defined by the `step`-size.

In [30]:
data_1D = np.arange(101)
data_1D

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

Explicitly defining the `start` and `end`. Both could be ommitted, because `start=0` and `end=101` are the first and last index. 

In [31]:
# start=0, end=101, step=10
data_1D[0:101:10]

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Ommitting the values for `start` and `end` as all values from start to end will be selected.

In [32]:
# step=10
data_1D[::10]

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Example for creating a crop. Have in mind that the endpoint will not be included.

In [37]:
start = 12
end = 50
data_1D = np.arange(101)
data_1D[start:end]

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49])

### Selecting values using negative indices
Using index `-1` will select the last element in the array. Using index `-2` will select the penultimate element and so on.

In [38]:
data_1D = np.arange(10)
print(data_1D)
print(f"index -1: {data_1D[-1]} - last element")
print(f"index -2: {data_1D[-2]} - penultimate element")

[0 1 2 3 4 5 6 7 8 9]
index -1: 9 - last element
index -2: 8 - penultimate element


But have in mind that **using the index `-1` as `end`-point** in order to crop a portion of the source array will **exclude the last element** of the source array.

In [39]:
data_1D[0:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

The zero as startpoint can be ommitted.

In [42]:
data_1D[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In order to extract a subset including the last value of the array, the `end`-point has to be defined explicitly or ommitting it.

In [46]:
# ommiting the end point to extract including the last value
data_1D[5:]

array([5, 6, 7, 8, 9])

In [47]:
# explicitily setting the end point to extract including the last value
data_1D[5:10]

array([5, 6, 7, 8, 9])

## Array multiplications
Types of multiplications

- Matrix with scalar<br>
`array * scalar`
- Element-wise product of two arrays<br>
`array_a * array_b or np.multiply(array_a, array_b)`
- Dot product of two arrays<br>
`array_a.dot(array_b) or np.dot(array_a, array_b)`

In [ ]:
array_a = np.arange(start=0,stop=4)
array_b = np.arange(start=2,stop=6)
print(array_a)
print(array_b)

[0 1 2 3]
[2 3 4 5]


In [ ]:
# array * scalar
scalar=3
array_a * scalar

array([0, 3, 6, 9])

In [ ]:
# element-wise multiplication (equivalent to Matlab: a .* b)
print(np.multiply(array_a, array_b))
print(array_a * array_b)

[ 0  3  8 15]
[ 0  3  8 15]


In [ ]:
array_a * array_b

array([ 0,  3,  8, 15])

## Stacking arrays in depth

In [ ]:
array_list = [np.arange(start=0, stop=10), np.arange(start=10, stop=20), np.arange(start=20, stop=30)]
print(array_list)
arrays_stacked = np.dstack(array_list)
print(arrays_stacked)
print('shape', arrays_stacked.shape)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])]
[[[ 0 10 20]
  [ 1 11 21]
  [ 2 12 22]
  [ 3 13 23]
  [ 4 14 24]
  [ 5 15 25]
  [ 6 16 26]
  [ 7 17 27]
  [ 8 18 28]
  [ 9 19 29]]]
shape (1, 10, 3)
